"""ProductImage.description nullable

Revision ID: 15c33a70af0b
Revises: d1538dd92edb
Create Date: 2024-05-17 10:22:29.650705

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "15c33a70af0b"
down_revision: Union[str, None] = "d1538dd92edb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_image", "description", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_image", "description", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    # ### end Alembic commands ###
