"""add price_markup to ProductVariation

Revision ID: 46622e7befc4
Revises: f84f27813da6
Create Date: 2024-07-24 17:17:45.282269

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "46622e7befc4"
down_revision: Union[str, None] = "f84f27813da6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variation",
        sa.Column("price_markup", sa.Integer(), server_default="0", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_variation", "price_markup")
    # ### end Alembic commands ###
