"""update ProductImage

Revision ID: 56155a7cd38d
Revises: 907bf646e78f
Create Date: 2024-05-04 17:21:33.079521

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "56155a7cd38d"
down_revision: Union[str, None] = "907bf646e78f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_image",
        sa.Column("description", sa.String(length=100), nullable=False, server_default=""),
    )
    op.execute("UPDATE product_image SET description = '' WHERE description is NULL")
    op.execute("update product_image set url = '' where url is NULL")
    op.execute("update product_image set original_url = '' where original_url is NULL")
    op.alter_column(
        "product_image",
        "url",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        server_default="",
    )
    op.alter_column(
        "product_image",
        "original_url",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        server_default="",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_image", "original_url", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("product_image", "url", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_column("product_image", "description")
    # ### end Alembic commands ###
