"""change Product & Category relationship

Revision ID: 6e950a7acb1a
Revises: 1efc78167598
Create Date: 2024-04-20 10:50:58.097653

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e950a7acb1a"
down_revision: Union[str, None] = "1efc78167598"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products_categories",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("category", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
    )
    op.drop_constraint("product_category_id_fkey", "product", type_="foreignkey")
    op.drop_column("product", "category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product", sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key(
        "product_category_id_fkey", "product", "category", ["category_id"], ["id"]
    )
    op.drop_table("products_categories")
    # ### end Alembic commands ###
