"""add original_url for ProductImage

Revision ID: 907bf646e78f
Revises: c12c569bf029
Create Date: 2024-05-04 17:16:43.786767

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "907bf646e78f"
down_revision: Union[str, None] = "c12c569bf029"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_image",
        sa.Column("original_url", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_image", "original_url")
    # ### end Alembic commands ###
