"""update ProductImage

Revision ID: ce56b26438b5
Revises: c12c569bf029
Create Date: 2024-05-05 09:45:40.499826

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce56b26438b5"
down_revision: Union[str, None] = "c12c569bf029"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("product_image", sa.Column("description", sa.String(length=100), nullable=False))
    op.alter_column(
        "product_image",
        "url",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
        existing_server_default=sa.text("''::character varying"),  # type: ignore
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product_image",
        "url",
        existing_type=sa.VARCHAR(length=255),
        nullable=True,
        existing_server_default=sa.text("''::character varying"),  # type: ignore
    )
    op.drop_column("product_image", "description")
    # ### end Alembic commands ###
