"""update variations relation

Revision ID: f84f27813da6
Revises: c2af1a6e1af4
Create Date: 2024-07-24 13:19:33.907416

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f84f27813da6"
down_revision: Union[str, None] = "c2af1a6e1af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products_variations",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("variation_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variation_id"],
            ["product_variation.id"],
        ),
    )
    op.drop_constraint(
        "product_variation_product_id_fkey", "product_variation", type_="foreignkey"
    )
    op.drop_column("product_variation", "product_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_variation",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "product_variation_product_id_fkey", "product_variation", "product", ["product_id"], ["id"]
    )
    op.drop_table("products_variations")
    # ### end Alembic commands ###
