"""update order

Revision ID: 37f41805de3a
Revises: b60accbfe77c
Create Date: 2024-08-18 10:49:48.906201

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37f41805de3a"
down_revision: Union[str, None] = "b60accbfe77c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_association",
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("variation_id", sa.Integer(), nullable=True),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["variation_id"],
            ["product_variation.id"],
        ),
        sa.PrimaryKeyConstraint("order_id", "product_id", "variation_id"),
    )
    op.drop_table("orders_products")
    op.alter_column("payment", "order_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payment", "order_id", existing_type=sa.INTEGER(), nullable=True)
    op.create_table(
        "orders_products",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], name="orders_products_order_id_fkey"),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name="orders_products_product_id_fkey"
        ),
    )
    op.drop_table("order_association")
    # ### end Alembic commands ###
