"""add position_order fields

Revision ID: c2af1a6e1af4
Revises: 15c33a70af0b
Create Date: 2024-05-18 14:17:46.604118

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2af1a6e1af4"
down_revision: Union[str, None] = "15c33a70af0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "category", sa.Column("position_order", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "product", sa.Column("position_order", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "product_image",
        sa.Column("position_order", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_image", "position_order")
    op.drop_column("product", "position_order")
    op.drop_column("category", "position_order")
    # ### end Alembic commands ###
