"""change order m2m to products

Revision ID: dc1a76b3cf44
Revises: 9c6623bed51a
Create Date: 2024-08-16 17:13:32.054302

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc1a76b3cf44"
down_revision: Union[str, None] = "9c6623bed51a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders_products",
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
    )
    op.drop_table("products_orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products_orders",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("order_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["order_id"], ["order.id"], name="products_orders_order_id_fkey"),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name="products_orders_product_id_fkey"
        ),
    )
    op.drop_table("orders_products")
    # ### end Alembic commands ###
