"""category: add is_coming

Revision ID: 0862b9320ecd
Revises: 52b0a03d3d76
Create Date: 2023-07-25 13:49:17.129276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0862b9320ecd'
down_revision = '52b0a03d3d76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_coming', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'is_coming')
    # ### end Alembic commands ###
