"""add product_variation

Revision ID: 46de8c52c1ed
Revises: 0862b9320ecd
Create Date: 2023-08-12 11:35:39.279725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "46de8c52c1ed"
down_revision = "0862b9320ecd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_variation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.Enum("size", "color", name="variationtype"), nullable=False),
        sa.Column("value", sa.String(length=50), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_variation")
    # ### end Alembic commands ###
