"""category: make slug unique

Revision ID: 888f058f4b33
Revises: 8adab4843269
Create Date: 2023-07-18 10:46:59.295160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "888f058f4b33"
down_revision = "8adab4843269"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category", ["slug"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "category", type_="unique")
    # ### end Alembic commands ###
