"""add category table

Revision ID: 8adab4843269
Revises:
Create Date: 2023-07-17 19:15:55.979361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8adab4843269"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=30), nullable=False),
        sa.Column("slug", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category")
    # ### end Alembic commands ###
