"""add payment

Revision ID: 92347f056b08
Revises: 540bd2625ab7
Create Date: 2023-08-16 10:28:58.462549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "92347f056b08"
down_revision = "540bd2625ab7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "payment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "waiting_for_capture", "succeeded", "canceled", name="paymentstatus"
            ),
            nullable=False,
        ),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("payment")
    # ### end Alembic commands ###
