"""order m2m add cascade

Revision ID: c68f797b3f74
Revises: 92347f056b08
Create Date: 2023-08-18 09:10:25.993927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c68f797b3f74"
down_revision = "92347f056b08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("product_order_order_id_fkey", "product_order", type_="foreignkey")
    op.drop_constraint("product_order_product_id_fkey", "product_order", type_="foreignkey")
    op.create_foreign_key(
        None, "product_order", "product", ["product_id"], ["id"], ondelete="cascade"
    )
    op.create_foreign_key(None, "product_order", "order", ["order_id"], ["id"], ondelete="cascade")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "product_order", type_="foreignkey")
    op.drop_constraint(None, "product_order", type_="foreignkey")
    op.create_foreign_key(
        "product_order_product_id_fkey", "product_order", "product", ["product_id"], ["id"]
    )
    op.create_foreign_key(
        "product_order_order_id_fkey", "product_order", "order", ["order_id"], ["id"]
    )
    # ### end Alembic commands ###
